import Foundation

struct AvailableLocalVoice: Sendable, Equatable {
    let model: LocalModel
    let resolved: ResolvedLocalModel
}

struct LocalSpeechQueueItem: Sendable, Equatable {
    let text: String
    let configuration: LocalTTSConfiguration
}

/// Plays speech generated by a downloaded sherpa-onnx model. The selected text never leaves the
/// machine and is never logged.
@MainActor final class SherpaTTSService: SpeechSynthesizing {
    static let defaultChunkCharacterLimit = SpeechTextChunker.defaultCharacterLimit

    private(set) var isSpeaking = false
    private(set) var isPaused = false
    var onStateChange: (@MainActor () -> Void)?
    var onError: (@MainActor (Error) -> Void)?

    private let modelManager: any ModelManaging
    private let generator: any LocalSpeechGenerating
    private let player: any AudioPlaying
    private let detector: any LanguageDetecting
    private let catalog: [LocalModel]
    private let chunkCharacterLimit: Int
    private var task: Task<Void, Never>?
    private var playback: CheckedContinuation<Void, Error>?
    private var heldAudio: Data?
    private var generation = 0

    init(modelManager: any ModelManaging,
         generator: any LocalSpeechGenerating,
         player: any AudioPlaying,
         detector: any LanguageDetecting = NLLanguageDetector(),
         catalog: [LocalModel] = ModelCatalog.all(kind: .tts),
         chunkCharacterLimit: Int = SherpaTTSService.defaultChunkCharacterLimit) {
        self.modelManager = modelManager
        self.generator = generator
        self.player = player
        self.detector = detector
        self.catalog = catalog
        self.chunkCharacterLimit = chunkCharacterLimit
    }

    func voices() -> [Voice] { [] }

    func availableVoices() async -> [AvailableLocalVoice] {
        var available: [AvailableLocalVoice] = []
        for model in catalog where model.kind == .tts {
            guard let resolved = await modelManager.resolved(model.id),
                  resolved.engine == model.engine,
                  resolved.directory != nil
            else { continue }
            available.append(AvailableLocalVoice(model: model, resolved: resolved))
        }
        return available
    }

    nonisolated static func localVoicePlan(
        text: String,
        settings: SpeechSettings,
        available: [AvailableLocalVoice],
        detector: any LanguageDetecting
    ) throws -> [PlannedSpeechRun<LocalVoiceSelection>] {
        let usable = available.filter {
            $0.model.kind == .tts
                && $0.resolved.engine == $0.model.engine
                && $0.resolved.directory != nil
        }
        guard let defaultID = settings.localModelID,
              let defaultVoice = usable.first(where: { $0.model.id == defaultID })
        else { throw MacomprendoError.modelMissing(settings.localModelID ?? "Local TTS") }
        let defaultSelection = clampedSelection(
            LocalVoiceSelection(modelID: defaultID, speakerID: settings.localSpeakerID),
            model: defaultVoice.model)

        return MixedLanguageSpeechPlanner.plan(
            text: text,
            enabled: settings.localSegmentationEnabled,
            defaultSelection: defaultSelection,
            detectLanguages: true,
            detector: detector
        ) { run, detectedLanguage in
            localVoiceSelection(
                for: run,
                detectedLanguage: detectedLanguage,
                settings: settings,
                available: usable,
                defaultVoice: defaultVoice,
                defaultSelection: defaultSelection)
        }
    }

    private nonisolated static func localVoiceSelection(
        for run: TextRun,
        detectedLanguage: String?,
        settings: SpeechSettings,
        available: [AvailableLocalVoice],
        defaultVoice: AvailableLocalVoice,
        defaultSelection: LocalVoiceSelection
    ) -> LocalVoiceSelection {
        guard run.script != .neutral else { return defaultSelection }

        if let language = detectedLanguage.map(baseLanguage) {
            if let mapped = settings.localVoiceByLanguage[language],
               let voice = available.first(where: { $0.model.id == mapped.modelID }),
               supports(language, model: voice.model) {
                return clampedSelection(mapped, model: voice.model)
            }
            if supports(language, model: defaultVoice.model) { return defaultSelection }
            if let automatic = available.first(where: { supports(language, model: $0.model) }) {
                return clampedSelection(
                    LocalVoiceSelection(modelID: automatic.model.id, speakerID: 0),
                    model: automatic.model)
            }
            return defaultSelection
        }

        if supports(run.script, model: defaultVoice.model) { return defaultSelection }
        if let automatic = available.first(where: { supports(run.script, model: $0.model) }) {
            return clampedSelection(
                LocalVoiceSelection(modelID: automatic.model.id, speakerID: 0),
                model: automatic.model)
        }
        return defaultSelection
    }

    private nonisolated static func clampedSelection(
        _ selection: LocalVoiceSelection,
        model: LocalModel
    ) -> LocalVoiceSelection {
        LocalVoiceSelection(
            modelID: selection.modelID,
            speakerID: min(max(selection.speakerID, 0), max(0, model.speakerCount - 1)))
    }

    private nonisolated static func supports(_ language: String, model: LocalModel) -> Bool {
        model.languages?.contains { baseLanguage($0) == baseLanguage(language) } == true
    }

    private nonisolated static func supports(_ script: ScriptClass, model: LocalModel) -> Bool {
        guard script != .neutral else { return false }
        return model.languages?.contains {
            LanguageSegmenter.script(ofLanguage: baseLanguage($0)) == script
        } == true
    }

    private nonisolated static func baseLanguage(_ language: String) -> String {
        language.split(separator: "-").first.map { $0.lowercased() } ?? ""
    }

    func speak(_ text: String, settings: SpeechSettings) {
        cancelCurrent()
        isPaused = false
        generation += 1
        let generation = self.generation

        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            setSpeaking(false)
            return
        }

        setSpeaking(true)
        task = Task { [weak self] in
            guard let self else { return }
            do {
                let queue = try await self.queue(text: text, settings: settings)
                try await self.play(queue)
                self.finish(generation: generation, error: nil)
            } catch {
                self.finish(generation: generation, error: error)
            }
        }
    }

    func stop() {
        generation += 1
        cancelCurrent()
        isPaused = false
        setSpeaking(false)
    }

    func pause() {
        guard isSpeaking, !isPaused else { return }
        player.pause()
        isPaused = true
        onStateChange?()
    }

    func resume() {
        guard isPaused else { return }
        isPaused = false
        if let audio = heldAudio {
            heldAudio = nil
            do { try player.play(audio) } catch { resumePlayback(throwing: error) }
        } else {
            player.resume()
        }
        onStateChange?()
    }

    /// Awaits the current speech job. Used by tests and the real-model smoke harness.
    func drain() async { _ = await task?.value }

    private func play(_ queue: [LocalSpeechQueueItem]) async throws {
        guard let first = queue.first else { return }
        var generated = try await generator.generate(
            first.text, configuration: first.configuration)

        for index in queue.indices {
            try Task.checkCancellation()
            if index + 1 < queue.count {
                let item = queue[index + 1]
                async let next = generator.generate(
                    item.text, configuration: item.configuration)
                try await playGenerated(generated)
                generated = try await next
            } else {
                try await playGenerated(generated)
            }
        }
    }

    private func playGenerated(_ generated: LocalSpeechAudio) async throws {
        try Task.checkCancellation()
        let wav = WAVEncoder.encode(pcm: generated.samples, sampleRate: generated.sampleRate)
        try await playAndWait(wav)
    }

    private func queue(text: String, settings: SpeechSettings) async throws -> [LocalSpeechQueueItem] {
        let available = await availableVoices()
        let plan = try Self.localVoicePlan(
            text: text, settings: settings, available: available, detector: detector)
        let finiteSpeed = settings.localSpeed.isFinite ? settings.localSpeed : 1
        let speed = min(max(finiteSpeed, 0.5), 2)
        let byID = Dictionary(uniqueKeysWithValues: available.map { ($0.model.id, $0) })

        return try plan.flatMap { run -> [LocalSpeechQueueItem] in
            guard let voice = byID[run.selection.modelID],
                  let directory = voice.resolved.directory
            else { throw MacomprendoError.modelMissing(run.selection.modelID) }
            let configuration = LocalTTSConfiguration(
                modelID: voice.model.id,
                engine: voice.resolved.engine,
                directory: directory,
                speakerID: run.selection.speakerID,
                speed: speed)
            return SpeechTextChunker.chunks(of: run.text, limit: chunkCharacterLimit).map {
                LocalSpeechQueueItem(text: $0, configuration: configuration)
            }
        }
    }

    private func cancelCurrent() {
        task?.cancel()
        task = nil
        heldAudio = nil
        resumePlayback(throwing: MacomprendoError.cancelled)
        player.stop()
    }

    private func finish(generation: Int, error: Error?) {
        guard generation == self.generation else { return }
        isPaused = false
        setSpeaking(false)
        guard let error, !Self.isCancellation(error) else { return }
        player.stop()
        onError?(error)
    }

    private func setSpeaking(_ value: Bool) {
        guard isSpeaking != value else { return }
        isSpeaking = value
        onStateChange?()
    }

    private func playAndWait(_ audio: Data) async throws {
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
                playback = continuation
                player.onFinished = { [weak self] in self?.resumePlayback(throwing: nil) }
                guard !isPaused else {
                    heldAudio = audio
                    return
                }
                do { try player.play(audio) } catch { resumePlayback(throwing: error) }
            }
        } onCancel: {
            Task { @MainActor [weak self] in
                self?.player.stop()
                self?.resumePlayback(throwing: CancellationError())
            }
        }
    }

    private func resumePlayback(throwing error: Error?) {
        guard let continuation = playback else { return }
        playback = nil
        player.onFinished = nil
        if let error { continuation.resume(throwing: error) } else { continuation.resume() }
    }

    private static func isCancellation(_ error: Error) -> Bool {
        error is CancellationError || (error as? MacomprendoError) == .cancelled
    }
}
