import Foundation

/// Plays speech generated by a downloaded sherpa-onnx model. The selected text never leaves the
/// machine and is never logged.
@MainActor final class SherpaTTSService: SpeechSynthesizing {
    static let defaultChunkCharacterLimit = SpeechTextChunker.defaultCharacterLimit

    private(set) var isSpeaking = false
    private(set) var isPaused = false
    var onStateChange: (@MainActor () -> Void)?
    var onError: (@MainActor (Error) -> Void)?

    private let modelManager: any ModelManaging
    private let generator: any LocalSpeechGenerating
    private let player: any AudioPlaying
    private let catalog: [LocalModel]
    private let chunkCharacterLimit: Int
    private var task: Task<Void, Never>?
    private var playback: CheckedContinuation<Void, Error>?
    private var heldAudio: Data?
    private var generation = 0

    init(modelManager: any ModelManaging,
         generator: any LocalSpeechGenerating,
         player: any AudioPlaying,
         catalog: [LocalModel] = ModelCatalog.all(kind: .tts),
         chunkCharacterLimit: Int = SherpaTTSService.defaultChunkCharacterLimit) {
        self.modelManager = modelManager
        self.generator = generator
        self.player = player
        self.catalog = catalog
        self.chunkCharacterLimit = chunkCharacterLimit
    }

    func voices() -> [Voice] { [] }

    func speak(_ text: String, settings: SpeechSettings) {
        cancelCurrent()
        isPaused = false
        generation += 1
        let generation = self.generation

        let chunks = SpeechTextChunker.chunks(of: text, limit: chunkCharacterLimit)
        guard !chunks.isEmpty else {
            setSpeaking(false)
            return
        }

        setSpeaking(true)
        task = Task { [weak self] in
            guard let self else { return }
            do {
                try await self.play(chunks: chunks, settings: settings)
                self.finish(generation: generation, error: nil)
            } catch {
                self.finish(generation: generation, error: error)
            }
        }
    }

    func stop() {
        generation += 1
        cancelCurrent()
        isPaused = false
        setSpeaking(false)
    }

    func pause() {
        guard isSpeaking, !isPaused else { return }
        player.pause()
        isPaused = true
        onStateChange?()
    }

    func resume() {
        guard isPaused else { return }
        isPaused = false
        if let audio = heldAudio {
            heldAudio = nil
            do { try player.play(audio) } catch { resumePlayback(throwing: error) }
        } else {
            player.resume()
        }
        onStateChange?()
    }

    /// Awaits the current speech job. Used by tests and the real-model smoke harness.
    func drain() async { _ = await task?.value }

    private func play(chunks: [String], settings: SpeechSettings) async throws {
        let configuration = try await configuration(settings)
        guard let first = chunks.first else { return }
        var generated = try await generator.generate(first, configuration: configuration)

        for index in chunks.indices {
            try Task.checkCancellation()
            if index + 1 < chunks.count {
                async let next = generator.generate(chunks[index + 1], configuration: configuration)
                try await playGenerated(generated)
                generated = try await next
            } else {
                try await playGenerated(generated)
            }
        }
    }

    private func playGenerated(_ generated: LocalSpeechAudio) async throws {
        try Task.checkCancellation()
        let wav = WAVEncoder.encode(pcm: generated.samples, sampleRate: generated.sampleRate)
        try await playAndWait(wav)
    }

    private func configuration(_ settings: SpeechSettings) async throws -> LocalTTSConfiguration {
        guard let modelID = settings.localModelID,
              let model = catalog.first(where: { $0.id == modelID && $0.kind == .tts })
        else { throw MacomprendoError.modelMissing(settings.localModelID ?? "Local TTS") }
        let speakerID = min(max(settings.localSpeakerID, 0), max(0, model.speakerCount - 1))
        let finiteSpeed = settings.localSpeed.isFinite ? settings.localSpeed : 1
        let speed = min(max(finiteSpeed, 0.5), 2)
        guard let resolved = await modelManager.resolved(modelID),
              resolved.engine == model.engine,
              let directory = resolved.directory
        else { throw MacomprendoError.modelMissing(modelID) }

        return LocalTTSConfiguration(
            modelID: modelID,
            engine: resolved.engine,
            directory: directory,
            speakerID: speakerID,
            speed: speed
        )
    }

    private func cancelCurrent() {
        task?.cancel()
        task = nil
        heldAudio = nil
        resumePlayback(throwing: MacomprendoError.cancelled)
        player.stop()
    }

    private func finish(generation: Int, error: Error?) {
        guard generation == self.generation else { return }
        isPaused = false
        setSpeaking(false)
        guard let error, !Self.isCancellation(error) else { return }
        player.stop()
        onError?(error)
    }

    private func setSpeaking(_ value: Bool) {
        guard isSpeaking != value else { return }
        isSpeaking = value
        onStateChange?()
    }

    private func playAndWait(_ audio: Data) async throws {
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<Void, Error>) in
                playback = continuation
                player.onFinished = { [weak self] in self?.resumePlayback(throwing: nil) }
                guard !isPaused else {
                    heldAudio = audio
                    return
                }
                do { try player.play(audio) } catch { resumePlayback(throwing: error) }
            }
        } onCancel: {
            Task { @MainActor [weak self] in
                self?.player.stop()
                self?.resumePlayback(throwing: CancellationError())
            }
        }
    }

    private func resumePlayback(throwing error: Error?) {
        guard let continuation = playback else { return }
        playback = nil
        player.onFinished = nil
        if let error { continuation.resume(throwing: error) } else { continuation.resume() }
    }

    private static func isCancellation(_ error: Error) -> Bool {
        error is CancellationError || (error as? MacomprendoError) == .cancelled
    }
}
